trigger:
  batch: true
  branches:
    include:
      - "*"

workspace:
    clean: all

variables:
  - group: "ESFA - SonarCloud"
  - group: 'Prod Management Resources'    
  - name: buildConfiguration
    value: 'release'
  - name: buildPlatform
    value: 'anycpu'

pool:
  name: DAS - Continuous Integration Agents
  demands: LATEST_DOTNET_VERSION -equals 3.1

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.10
    endpoint: SkillsFundingAgency

steps:
- template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

- template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
  parameters:
    SonarCloud: true
    SonarCloudProjectKey: SkillsFundingAgency_das-roatp-assessor

- template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks  

- task: DotNetCoreCLI@2
  displayName: 'Publish WebApp'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/SFA.DAS.RoatpAssessor/SFA.DAS.RoatpAssessor.Web/SFA.DAS.RoatpAssessor.Web.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: |
     azure/**
     config/**
    TargetFolder: '$(build.artifactstagingdirectory)/publish'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/publish'
